---
dist: focal

language: python

env:
  global:
    - ROLE_NAME: minio_podman
    - AUTHOR_NAME: smlloyd

before_install:
- . /etc/os-release
- sudo sh -c "echo 'deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/ /' > /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list"
- curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/Release.key | sudo apt-key add -
- sudo apt-get update -qq
- sudo apt-get install -qq -y software-properties-common podman
- sudo mkdir -p /etc/containers
- sudo sh -c '/bin/echo -e "[registries.search]\nregistries = [\"docker.io\"]" > /etc/containers/registries.conf'
- podman --version

  ## Install ansible
  #addons:
  #  apt:
  #    packages:
  #    - python-pip

install:
  # Install ansible
  - sudo pip install ansible ansible-lint

  # Check ansible version
  - ansible --version

before_script:
  # Use galaxy role name
  - cd ../
  - mv ansible-role-$ROLE_NAME $AUTHOR_NAME.$ROLE_NAME
  - cd $AUTHOR_NAME.$ROLE_NAME
  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  - ansible-lint */*.yml
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  # Run first time
  - ansible-playbook tests/test.yml -i tests/inventory --diff
  # Run second time
  - ansible-playbook tests/test.yml -i tests/inventory --diff

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
